"""add model to level

Revision ID: d1aac213d3d3
Revises: 88ddf00f7a0e
Create Date: 2026-03-09 02:26:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aac213d3d3'
down_revision = '88ddf00f7a0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('model', sa.String(length=255), server_default='llama-3.3-70b-versatile', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'model')
    # ### end Alembic commands ###
