"""drop secret_key

Revision ID: 72c0d536959b
Revises: b2c3d4e5f6a7
Create Date: 2026-03-12 22:08:58.653810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c0d536959b'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_level_state', 'secret_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_level_state', sa.Column('secret_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
